import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

import { getEntries } from "./api/contentful";
import ArticleTeaser from "@/components/ArticleTeaser/ArticleTeaser";

const inter = Inter({ subsets: ["latin"] });

export async function getStaticProps() {
  const news = await getEntries({
    content_type: "nieuws",
    order: "-fields.date",
  });

  return {
    props: {
      news: news.items,
    },
  };
}

const Home = ({ news }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ul>
          {news.map((news) => (
            <ArticleTeaser key={news.sys.id} news={news} />
          ))}
        </ul>
      </main>
    </>
  );
};

export default Home;
