import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

import { getEntries } from "./api/contentful";

const inter = Inter({ subsets: ["latin"] });

export async function getStaticProps() {
  const news = await getEntries({ content_type: "nieuws" });

  return {
    props: {
      nieuwsContent: news.items,
    },
  };
}

export default function Home({ nieuwsContent }) {
  console.log(nieuwsContent);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}></main>
    </>
  );
}
